// react-chat/src/messages/messages.js
import React, { Component } from 'react';
import './messages.scss';
import axios from "axios";
import Icon from "@material-ui/core/Icon";
import { Stomp } from 'stompjs/lib/stomp.js';

export class Messages extends Component {

    server = 'http://localhost:8000';
    webSocket = 'ws://localhost:8000/socket';

    constructor(props) {
        super(props);
        this.state = {messages: [], message: ''};
        this.sendMessage = this.sendMessage.bind(this);
        this.handleMessageChange = this.handleMessageChange.bind(this);
    }

    componentDidMount() {
        axios.get(`${this.server}/messages`)
            .then(response => {
                const messages = response.data.map(message => ({...message, date: new Date(message.date)}));
                this.setState({messages: messages})
            });
        this.connect();
    }

    componentWillUnmount() {
        this.disconnect();
    }

    sendMessage(event) {
        event.preventDefault();
        if (this.state.message !== '') {
            let body = {
                text: this.state.message,
                userId: this.props.user.id
            };
            return axios.post(`${this.server}/messages/new`, body)
                .then(() => this.setState({message: ''}));
        }
    }

    handleMessageChange(event) {
        this.setState({message: event.target.value});
    }

    displayMessages() {
        let messages = this.state.messages.map(message => {
            return (
                <div key={message.id} className={this.isCurrentUser(message.userId) ? 'current-user' : 'other-user'}>
                    <div className="bubble">
                        <div className="user-name">
                            {message.userName}
                        </div>
                        <div className="message-text">
                            <span className="margin-right-10">{message.text}</span>
                            {Messages.isToday(message.date) ? (
                                <span
                                    className="message-date">{Messages.getDateWithFormat(message.date, true)}</span>) : null}
                        </div>
                        {!Messages.isToday(message.date) ? (
                            <div
                                className="message-date">{Messages.getDateWithFormat(message.date, false)}</div>) : null}
                    </div>
                </div>
            )
        });
        return <div className="messages">{messages}</div>;
    }

    connect() {
        let socket = new WebSocket(this.webSocket);
        this.ws = Stomp.over(socket);
        this.ws.connect({}, () => {
            this.ws.subscribe('/chat', frame => {
                const message = JSON.parse(frame.body);
                const formatedMessage = {...message, date: new Date(message.date)};
                this.setState({messages: [...this.state.messages, formatedMessage]});
            });
        }, (error) => {
            alert(`STOMP error ${error}`);
        });
    }

    disconnect() {
        if (this.ws != null) {
            this.ws.ws.close();
        }
        console.warn('Disconnected');
    }

    isCurrentUser(userId) {
        return userId === this.props.user.id;
    }

    static isToday(date) {
        const today = new Date();
        return date.getDate() === today.getDate()
            && date.getMonth() === today.getMonth()
            && date.getFullYear() === today.getFullYear();
    }

    render() {
        return (
            <div className="message-component">
                <div className="message-container">
                    {this.displayMessages()}
                </div>
                <form className="message-form" onSubmit={this.sendMessage}>
                    <input type="text" value={this.state.message} onChange={this.handleMessageChange}
                           placeholder="Write your message..."/>
                    <div className="send-button">
                        <button type=" submit">
                            <Icon>send</Icon>
                        </button>
                    </div>
                </form>
            </div>
        )
    }

    static getDateWithFormat(date, isToday) {
        let options;
        if (isToday) {
            options = {minute: 'numeric', second: 'numeric'};
        } else {
            options = {year: 'numeric', month: 'long', day: 'numeric'};
        }
        return new Intl.DateTimeFormat('en-GB', options).format(date);
    }
}

// angular-chat/src/app/messages/messages.component.ts
import { AfterViewInit, Component, ElementRef, Input, OnDestroy, OnInit, ViewChild } from '@angular/core';
import { FormControl } from '@angular/forms';
import { Stomp } from 'stompjs/lib/stomp.js';
import { MessageService } from './message.service';
import { Message } from './message.interface';
import { User } from '../user/user.interface';
import { environment } from '../../environments/environment';

@Component({
  selector: 'app-messages',
  templateUrl: './messages.component.html',
  styleUrls: ['./messages.component.scss']
})
export class MessagesComponent implements OnInit, OnDestroy, AfterViewInit {

  @Input()
  user: User;

  @ViewChild('messageInput')
  messageInput: ElementRef;

  messages: Message[] = [];
  name = new FormControl('');
  ws: any;

  constructor(private messageService: MessageService) {
  }

  ngOnInit(): void {
    this.connect();
    this.messageService.getMessages().then((messages: Message[]) => {
      this.messages = messages;
    });
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.messageInput.nativeElement.focus());
  }

  ngOnDestroy(): void {
    this.disconnect();
  }

  connect() {
    let socket = new WebSocket(environment.webSocket);
    this.ws = Stomp.over(socket);
    this.ws.connect({}, () => {
      this.ws.subscribe('/chat', (frame: { body: string }) => {
        const message: Message = JSON.parse(frame.body);
        this.messages.push({...message, date: new Date(message.date)});
      });
    }, (error) => {
      alert('STOMP error ' + error);
    });
  }

  disconnect() {
    if (this.ws != null) {
      this.ws.ws.close();
    }
    console.warn('Disconnected');
  }

  send() {
    this.messageService.send({
      text: this.name.value,
      userId: this.user.id
    });
    this.name.setValue('');
  }

  isToday(date: Date) {
    const today = new Date();
    return date.getDate() == today.getDate()
      && date.getMonth() == today.getMonth()
      && date.getFullYear() == today.getFullYear();
  }

  isCurrentUser(userId: string) {
    return userId === this.user.id;
  }
}

<div class="message-component">
  <div #scroll [scrollTop]="scroll.scrollHeight" class="message-container">
    <div class="messages">
      <div *ngFor="let message of messages"
           [ngClass]="{'current-user': isCurrentUser(message.userId), 'other-user': !isCurrentUser(message.userId)}">
        <div class="bubble">
          <div *ngIf="!isCurrentUser(message.userId)" class="user-name">
            {{message.userName}}
          </div>
          <div class="message-text">
            <span class="margin-right-10">{{message.text}}</span>
            <span *ngIf="isToday(message.date)" class="message-date">
              {{message.date | date:'hh:mm'}}
            </span>
          </div>
          <div *ngIf="!isToday(message.date)" class="message-date">
            {{message.date | date:'dd MMM yyyy'}}
          </div>
        </div>
      </div>
    </div>
  </div>
  <form (submit)="send()" class="message-form">
    <input #messageInput [formControl]="name" placeholder="Write your message..." type="text">
    <div class="send-button">
      <button [disabled]="name.value === ''" type="submit">
        send
      </button>
    </div>
  </form>
</div>
