// react-chat/src/App.js
import React, {Component} from 'react';
import './App.scss';
import axios from 'axios';
import {Messages} from './messages/messages';
import Button from '@material-ui/core/Button';

class App extends Component {

    server = 'http://localhost:8000';

    constructor(props) {
        super(props);

        this.state = {
            user: null,
            userName: ''
        };
        this.activeUser = this.activeUser.bind(this);
        this.handleUserNameChange = this.handleUserNameChange.bind(this);
    }

    handleUserNameChange(event) {
        this.setState({userName: event.target.value});
    }

    render() {
        return (
            <div className="application-component">
                <div className="application-container">
                    {this.state.user ? this.displayMessages() : this.displayUserInput()}
                </div>
            </div>
        );
    }

    displayUserInput() {
        return (
            <div className="userForm">
                <h1 className="marginBottom15">
                    Welcome to the chat
                </h1>
                <div className="marginBottom15">
                    What is your name ?
                </div>
                <form onSubmit={this.activeUser}>
                    <input className="marginBottom15" type="text" value={this.state.userName}
                           onChange={this.handleUserNameChange}/>
                    <Button type="submit" variant="contained" color="primary">
                        Let's go!
                    </Button>
                </form>
            </div>
        );
    }

    displayMessages() {
        return <Messages user={this.state.user}></Messages>;
    }

    activeUser(event) {
        event.preventDefault();
        let name = this.state.userName;
        if (name !== '') {
            return axios.post(`${this.server}/users`, {name: this.state.userName}).then(response => {
                    this.setState({user: response.data});
                },
                (error) => console.error(error));
        }
    }
}

export default App;

// angular-chat/src/app/app.component.ts
import { AfterViewInit, Component, ElementRef, ViewChild } from "@angular/core";
import { FormControl } from "@angular/forms";
import { UserService } from "./user/user.service";
import { User } from "./user/user.interface";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.scss"]
})
export class AppComponent implements AfterViewInit {

  @ViewChild("userInput")
  userInput: ElementRef;

  userName = new FormControl<string>("");

  user: User;

  constructor(public userService: UserService) {
  }

  ngAfterViewInit(): void {
    setTimeout(() => this.userInput.nativeElement.focus());
  }

  activateUser() {
    if (this.userName.value && this.userName.value !== "") {
      this.userService.getUser(this.userName.value)
        .then(user => this.user = user);
    }
  }
}

<div class="application-component" data-cy="application-component">
  <div class="application-container">
    <ng-container *ngIf="!user">
      <div class="userForm" data-cy="user-form">
        <h1 class="marginBottom15">
          Welcome to the chat
        </h1>
        <div class="marginBottom15">
          What is your name ?
        </div>
        <form (submit)="activateUser()">
          <input #userInput [formControl]="userName" class="marginBottom15" type="text">
          <button *ngIf="userName.value" type="submit">
            Let's go!
          </button>
        </form>
      </div>
    </ng-container>
    <ng-container *ngIf="user">
      <app-messages [user]="user"></app-messages>
    </ng-container>
  </div>
</div>
