// react-chat/src/App.js
import React, {Component} from 'react';
import './App.scss';
import axios from 'axios';
import {Messages} from './messages/messages';
import Button from '@material-ui/core/Button';

class App extends Component {

    server = 'http://localhost:8000';

    constructor(props) {
        super(props);

        this.state = {
            user: null,
            userName: ''
        };
        this.activeUser = this.activeUser.bind(this);
        this.handleUserNameChange = this.handleUserNameChange.bind(this);
    }

    handleUserNameChange(event) {
        this.setState({userName: event.target.value});
    }

    render() {
        return (
            <div className="application-component">
                <div className="application-container">
                    {this.state.user ? this.displayMessages() : this.displayUserInput()}
                </div>
            </div>
        );
    }

    displayUserInput() {
        return (
            <div className="userForm">
                <h1 className="marginBottom15">
                    Welcome to the chat
                </h1>
                <div className="marginBottom15">
                    What is your name ?
                </div>
                <form onSubmit={this.activeUser}>
                    <input className="marginBottom15" type="text" value={this.state.userName}
                           onChange={this.handleUserNameChange}/>
                    <Button type="submit" variant="contained" color="primary">
                        Let's go!
                    </Button>
                </form>
            </div>
        );
    }

    displayMessages() {
        return <Messages user={this.state.user}></Messages>;
    }

    activeUser(event) {
        event.preventDefault();
        let name = this.state.userName;
        if (name !== '') {
            return axios.post(`${this.server}/users`, {name: this.state.userName}).then(response => {
                    this.setState({user: response.data});
                },
                (error) => console.error(error));
        }
    }
}

export default App;

// vue-chat/src/App.vue
<template>
    <div class="application-component">
        <div class="application-container">
            <div class="userForm" v-if="!user">
                <h1 class="marginBottom15">
                    Welcome to the chat
                </h1>
                <div class="marginBottom15">
                    What is your name ?
                </div>
                <form @submit="activeUser">
                    <input type="text" v-model="userName" class="marginBottom15">
                    <button type="submit" v-bind:aria-disabled="userName === ''">
                        Let's go!
                    </button>
                </form>
            </div>
            <messages v-else :user="user"></messages>
        </div>
    </div>
</template>

<script lang="ts">
    import { Component, Vue } from 'vue-property-decorator';
    import { User } from '@/user.interface';
    import axios, { AxiosResponse } from 'axios';
    import Messages from '@/components/Messages.vue';

    const server = 'http://localhost:8000';

    @Component({
        components: {
            messages: Messages,
        },
    })
    export default class App extends Vue {

        public userName: string;
        public user: User | null;

        constructor() {
            super();
            this.userName = '';
            this.user = null;
        }

        public activeUser(e: Event) {
            e.preventDefault();
            if ( this.userName ) {
                return axios.post(`${server}/users`, {name: this.userName}).then((response: AxiosResponse) => {
                    this.user = response ? response.data : null;
                    this.userName = '';
                });
            }
        }
    }
</script>

<style lang="scss">
    @import url('https://fonts.googleapis.com/css?family=Roboto');
    @import url('https://fonts.googleapis.com/icon?family=Material+Icons');

    html, body, #root {
        height: 100%;
        margin: 0;
    }

    body {
        margin: 0;
        font-family: Roboto, "Helvetica Neue", sans-serif;
        background-color: #D9DBD6;
    }

    .application-component {
        width: 100%;
        height: 100%;
        min-width: 100%;
        min-height: 100%;
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center;
        align-content: center;

        &::before {
            content: '';
            width: 100%;
            height: 200px;
            position: absolute;
            background-color: #3798D4;
            top: 0;
            z-index: -1;
        }

        .application-container {
            display: flex;
            flex-direction: row;
            justify-content: center;
            align-items: center;
            align-content: center;
            border-radius: 3px;
            box-shadow: 0 1px 1px 0 rgba(0, 0, 0, 0.06), 0 2px 5px 0 rgba(0, 0, 0, 0.2);
            background-color: #ffffff;
            font-size: 24px;

            @media (min-width: 1919px) {
                width: 60%;
                height: 90%;
            }

            .userForm {
                display: flex;
                flex-direction: column;
                justify-content: center;
                align-items: center;
                align-content: center;

                .marginBottom15 {
                    margin-bottom: 15px;
                }


                h1 {
                    @media (max-width: 1200px) {
                        font-size: 30px;
                    }
                }

                form {
                    display: flex;
                    flex-direction: column;
                    justify-content: center;
                    align-items: center;
                    align-content: center;

                    input {
                        font-size: 22px;
                        width: 300px;
                        border: 2px solid #aaa;
                        border-radius: 4px;
                        margin: 8px 0;
                        outline: none;
                        padding: 15px;
                        box-sizing: border-box;
                        transition: .3s;
                    }

                    input[type=text]:focus {
                        border-color: dodgerBlue;
                        box-shadow: 0 0 8px 0 dodgerBlue;
                    }

                    button {
                        vertical-align: middle;
                        padding: 10px 20px;
                        font-size: 22px;
                        color: #ffffff;
                        text-decoration: none;
                        background-color: #3798D4;
                        text-align: center;
                        letter-spacing: .5px;
                        height: 50px;
                        line-height: 36px;
                        text-transform: uppercase;
                        border: none;
                        border-radius: 2px;
                        outline: 0;
                        position: relative;
                        cursor: pointer;
                        display: inline-block;
                        overflow: hidden;
                    }

                }
            }
        }
    }
</style>
