// react-chat/src/App.js
import React, {Component} from 'react';
import './App.scss';
import axios from 'axios';
import {Messages} from './messages/messages';
import Button from '@material-ui/core/Button';

class App extends Component {

    server = 'http://localhost:8000';

    constructor(props) {
        super(props);

        this.state = {
            user: null,
            userName: ''
        };
        this.activeUser = this.activeUser.bind(this);
        this.handleUserNameChange = this.handleUserNameChange.bind(this);
    }

    handleUserNameChange(event) {
        this.setState({userName: event.target.value});
    }

    render() {
        return (
            <div className="application-component">
                <div className="application-container">
                    {this.state.user ? this.displayMessages() : this.displayUserInput()}
                </div>
            </div>
        );
    }

    displayUserInput() {
        return (
            <div className="userForm">
                <h1 className="marginBottom15">
                    Welcome to the chat
                </h1>
                <div className="marginBottom15">
                    What is your name ?
                </div>
                <form onSubmit={this.activeUser}>
                    <input className="marginBottom15" type="text" value={this.state.userName}
                           onChange={this.handleUserNameChange}/>
                    <Button type="submit" variant="contained" color="primary">
                        Let's go!
                    </Button>
                </form>
            </div>
        );
    }

    displayMessages() {
        return <Messages user={this.state.user}></Messages>;
    }

    activeUser(event) {
        event.preventDefault();
        let name = this.state.userName;
        if (name !== '') {
            return axios.post(`${this.server}/users`, {name: this.state.userName}).then(response => {
                    this.setState({user: response.data});
                },
                (error) => console.error(error));
        }
    }
}

export default App;

// doodle-front/src/app/app.component.ts
import { Component } from '@angular/core';
import { FormControl } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

// TODO move interface
export interface User {
  name: string;
  id: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {

  userName = new FormControl('');

  user: User;

  constructor(private http: HttpClient) {
    console.log(this.user)
  }

  activateUser() {
    if ( this.userName.value && this.userName.value !== '' ) {
      this.http.post<User>('http://localhost:8000/users', {name: this.userName.value}).toPromise()
        .then(user => this.user = user);
    }
  }
}

<div>
  <ng-container *ngIf="!user">
    What is your name ?
    <input type="text" [formControl]="userName">
    <button (click)="activateUser()">send</button>
  </ng-container>
  <ng-container *ngIf="user">
    <app-messages [user]="user"></app-messages>
  </ng-container>
</div>
